<a href="https://colab.research.google.com/github/greypen2006/biophilic-design/blob/main/PR_Report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving productDownload_2025-12-20T064524.zip to productDownload_2025-12-20T064524.zip

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import random
%matplotlib inline

In [4]:
import zipfile
import io

# The uploaded variable contains the content of the zip file
zip_file_content = uploaded['productDownload_2025-12-20T064524.zip']

# Create a ZipFile object from the bytes content
with zipfile.ZipFile(io.BytesIO(zip_file_content), 'r') as zf:
    # Extract all contents of the zip file
    zf.extractall('.')
print("Zip file extracted.")

Zip file extracted.

In [6]:
df_2012 = pd.read_csv('ACSDP1Y2012.DP04-Data.csv')
display(df_2012.head())

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0139PM,DP04_0140E,DP04_0140M,DP04_0140PE,DP04_0140PM,DP04_0141E,DP04_0141M,DP04_0141PE,DP04_0141PM,Unnamed: 566
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing units,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,Estimate!!HOUSING OCCUPANCY!!Occupied housing ...,Margin of Error!!HOUSING OCCUPANCY!!Occupied h...,Percent!!HOUSING OCCUPANCY!!Occupied housing u...,Percent Margin of Error!!HOUSING OCCUPANCY!!Oc...,...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,NaN
1,0400000US72,Puerto Rico,1583437,6946,1583437,(X),1263694,9111,79.8,0.4,...,1.0,99823,4724,47.5,1.8,175682,5131,(X),(X),NaN
2,312M100US419807276770,"San Juan zona urbana, PR; San Juan-Caguas-Guay...",187413,2095,187413,(X),147722,3048,78.8,1.3,...,2.1,23938,2199,49.9,3.8,21976,1893,(X),(X),NaN

In [7]:
df_2013 = pd.read_csv('ACSDP1Y2013.DP04-Data.csv')
display(df_2013.head())

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0139PM,DP04_0140E,DP04_0140M,DP04_0140PE,DP04_0140PM,DP04_0141E,DP04_0141M,DP04_0141PE,DP04_0141PM,Unnamed: 566
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing units,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,Estimate!!HOUSING OCCUPANCY!!Total housing uni...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing unit...,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,NaN
1,0400000US72,Puerto Rico,1572849,6980,1572849,(X),1253690,9187,79.7,0.5,...,1.0,104162,4804,47.7,1.9,169785,6466,(X),(X),NaN
2,312M200US419807276770,"San Juan zona urbana, PR; San Juan-Carolina-Ca...",187257,2209,187257,(X),144134,2908,77.0,1.2,...,2.4,22251,2173,48.6,3.8,21881,1973,(X),(X),NaN

In [8]:
df_2014 = pd.read_csv('ACSDP1Y2014.DP04-Data.csv')
display(df_2014.head())

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0139PM,DP04_0140E,DP04_0140M,DP04_0140PE,DP04_0140PM,DP04_0141E,DP04_0141M,DP04_0141PE,DP04_0141PM,Unnamed: 566
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing units,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,Estimate!!HOUSING OCCUPANCY!!Total housing uni...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing unit...,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,NaN
1,0400000US72,Puerto Rico,1571275,7659,1571275,(X),1233490,9061,78.5,0.5,...,1.0,103032,4656,47.7,1.8,179755,5703,(X),(X),NaN
2,312M200US419807276770,"San Juan zona urbana, PR; San Juan-Carolina-Ca...",186678,2255,186678,(X),143569,3570,76.9,1.6,...,2.3,21886,2134,45.9,3.7,20713,1870,(X),(X),NaN

In [9]:
df_2015 = pd.read_csv('ACSDP1Y2015.DP04-Data.csv')
display(df_2015.head())

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0141PM,DP04_0142E,DP04_0142M,DP04_0142PE,DP04_0142PM,DP04_0143E,DP04_0143M,DP04_0143PE,DP04_0143PM,Unnamed: 574
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing units,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,Estimate!!HOUSING OCCUPANCY!!Total housing uni...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing unit...,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,NaN
1,0400000US72,Puerto Rico,1573532,7851,1573532,(X),1221851,9077,77.7,0.4,...,1.1,103557,4974,48.1,1.6,169577,5393,(X),(X),NaN
2,312M200US419807276770,"San Juan zona urbana, PR; San Juan-Carolina-Ca...",188607,2100,188607,(X),138436,3080,73.4,1.6,...,2.4,20924,2140,48.3,3.9,23198,2272,(X),(X),NaN

In [10]:
df_2016 = pd.read_csv('ACSDP1Y2016.DP04-Data.csv')
display(df_2016.head())

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0141PM,DP04_0142E,DP04_0142M,DP04_0142PE,DP04_0142PM,DP04_0143E,DP04_0143M,DP04_0143PE,DP04_0143PM,Unnamed: 574
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing units,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,Estimate!!HOUSING OCCUPANCY!!Total housing uni...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing unit...,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,NaN
1,0400000US72,Puerto Rico,1555880,8239,1555880,(X),1208438,9900,77.7,0.6,...,1.0,94321,5016,44.5,2.0,174729,6057,(X),(X),NaN
2,312M300US419807276770,"San Juan zona urbana, PR; San Juan-Carolina-Ca...",187192,2833,187192,(X),141983,3598,75.8,1.5,...,1.9,21982,2299,45.4,3.6,20933,1949,(X),(X),NaN

In [11]:
df_2017 = pd.read_csv('ACSDP1Y2017.DP04-Data.csv')
display(df_2017.head())

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0141PM,DP04_0142E,DP04_0142M,DP04_0142PE,DP04_0142PM,DP04_0143E,DP04_0143M,DP04_0143PE,DP04_0143PM,Unnamed: 574
0,Geography,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing units,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,Estimate!!HOUSING OCCUPANCY!!Total housing uni...,Margin of Error!!HOUSING OCCUPANCY!!Total hous...,Percent!!HOUSING OCCUPANCY!!Total housing unit...,Percent Margin of Error!!HOUSING OCCUPANCY!!To...,...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEH...,Margin of Error!!GROSS RENT AS A PERCENTAGE OF...,Percent!!GROSS RENT AS A PERCENTAGE OF HOUSEHO...,Percent Margin of Error!!GROSS RENT AS A PERCE...,NaN
1,0400000US72,Puerto Rico,1561802,7656,1561802,(X),1191305,10722,76.3,0.5,...,1.2,90344,5791,44.0,1.9,184063,7362,(X),(X),NaN
2,312M300US419807276770,"San Juan zona urbana, PR; San Juan-Carolina-Ca...",182867,2618,182867,(X),135460,3252,74.1,1.5,...,2.7,21764,2241,49.1,4.1,17741,2041,(X),(X),NaN

In [12]:
dataframes = {
    'df_2012': df_2012,
    'df_2013': df_2013,
    'df_2014': df_2014,
    'df_2015': df_2015,
    'df_2016': df_2016,
    'df_2017': df_2017
}

for name, df_obj in dataframes.items():
    print(f"Cleaning {name}...")
    # Apply replace operations to all columns of type object
    for col in df_obj.select_dtypes(include=['object']).columns:
        df_obj[col] = df_obj[col].replace(',', '', regex=True)
        df_obj[col] = df_obj[col].replace('-', np.nan, regex=True)

    # Attempt to convert all suitable columns to float, coercing errors
    # We'll skip the first two columns (GEO_ID, NAME) as they are identifiers
    for col in df_obj.columns[2:]:
        df_obj[col] = pd.to_numeric(df_obj[col], errors='coerce')

    # Update the original dataframe in the global scope
    globals()[name] = df_obj

    print(f"Head of cleaned {name}:")
    display(df_obj.head())
    print("\n")

Cleaning df_2012...
Head of cleaned df_2012:

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0139PM,DP04_0140E,DP04_0140M,DP04_0140PE,DP04_0140PM,DP04_0141E,DP04_0141M,DP04_0141PE,DP04_0141PM,Unnamed: 566
0,Geography,Geographic Area Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0400000US72,Puerto Rico,1583437.0,6946.0,1583437.0,NaN,1263694.0,9111.0,79.8,0.4,...,1.0,99823.0,4724.0,47.5,1.8,175682.0,5131.0,NaN,NaN,NaN
2,312M100US419807276770,NaN,187413.0,2095.0,187413.0,NaN,147722.0,3048.0,78.8,1.3,...,2.1,23938.0,2199.0,49.9,3.8,21976.0,1893.0,NaN,NaN,NaN

Cleaning df_2013...
Head of cleaned df_2013:

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0139PM,DP04_0140E,DP04_0140M,DP04_0140PE,DP04_0140PM,DP04_0141E,DP04_0141M,DP04_0141PE,DP04_0141PM,Unnamed: 566
0,Geography,Geographic Area Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0400000US72,Puerto Rico,1572849.0,6980.0,1572849.0,NaN,1253690.0,9187.0,79.7,0.5,...,1.0,104162.0,4804.0,47.7,1.9,169785.0,6466.0,NaN,NaN,NaN
2,312M200US419807276770,NaN,187257.0,2209.0,187257.0,NaN,144134.0,2908.0,77.0,1.2,...,2.4,22251.0,2173.0,48.6,3.8,21881.0,1973.0,NaN,NaN,NaN

Cleaning df_2014...
Head of cleaned df_2014:

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0139PM,DP04_0140E,DP04_0140M,DP04_0140PE,DP04_0140PM,DP04_0141E,DP04_0141M,DP04_0141PE,DP04_0141PM,Unnamed: 566
0,Geography,Geographic Area Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0400000US72,Puerto Rico,1571275.0,7659.0,1571275.0,NaN,1233490.0,9061.0,78.5,0.5,...,1.0,103032.0,4656.0,47.7,1.8,179755.0,5703.0,NaN,NaN,NaN
2,312M200US419807276770,NaN,186678.0,2255.0,186678.0,NaN,143569.0,3570.0,76.9,1.6,...,2.3,21886.0,2134.0,45.9,3.7,20713.0,1870.0,NaN,NaN,NaN

Cleaning df_2015...
Head of cleaned df_2015:

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0141PM,DP04_0142E,DP04_0142M,DP04_0142PE,DP04_0142PM,DP04_0143E,DP04_0143M,DP04_0143PE,DP04_0143PM,Unnamed: 574
0,Geography,Geographic Area Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0400000US72,Puerto Rico,1573532.0,7851.0,1573532.0,NaN,1221851.0,9077.0,77.7,0.4,...,1.1,103557.0,4974.0,48.1,1.6,169577.0,5393.0,NaN,NaN,NaN
2,312M200US419807276770,NaN,188607.0,2100.0,188607.0,NaN,138436.0,3080.0,73.4,1.6,...,2.4,20924.0,2140.0,48.3,3.9,23198.0,2272.0,NaN,NaN,NaN

Cleaning df_2016...
Head of cleaned df_2016:

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0141PM,DP04_0142E,DP04_0142M,DP04_0142PE,DP04_0142PM,DP04_0143E,DP04_0143M,DP04_0143PE,DP04_0143PM,Unnamed: 574
0,Geography,Geographic Area Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0400000US72,Puerto Rico,1555880.0,8239.0,1555880.0,NaN,1208438.0,9900.0,77.7,0.6,...,1.0,94321.0,5016.0,44.5,2.0,174729.0,6057.0,NaN,NaN,NaN
2,312M300US419807276770,NaN,187192.0,2833.0,187192.0,NaN,141983.0,3598.0,75.8,1.5,...,1.9,21982.0,2299.0,45.4,3.6,20933.0,1949.0,NaN,NaN,NaN

Cleaning df_2017...
Head of cleaned df_2017:

,GEO_ID,NAME,DP04_0001E,DP04_0001M,DP04_0001PE,DP04_0001PM,DP04_0002E,DP04_0002M,DP04_0002PE,DP04_0002PM,...,DP04_0141PM,DP04_0142E,DP04_0142M,DP04_0142PE,DP04_0142PM,DP04_0143E,DP04_0143M,DP04_0143PE,DP04_0143PM,Unnamed: 574
0,Geography,Geographic Area Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0400000US72,Puerto Rico,1561802.0,7656.0,1561802.0,NaN,1191305.0,10722.0,76.3,0.5,...,1.2,90344.0,5791.0,44.0,1.9,184063.0,7362.0,NaN,NaN,NaN
2,312M300US419807276770,NaN,182867.0,2618.0,182867.0,NaN,135460.0,3252.0,74.1,1.5,...,2.7,21764.0,2241.0,49.1,4.1,17741.0,2041.0,NaN,NaN,NaN

Change columns to Geographic Area Name (as index?), Year, Total Housing Units, Margin of Error, Vacant Housing Units, Margin of error, Percentage of vacancy, Income percentage less than 50,000; margin of error; income percentage 50,000-99,999; MOE; 100,000 to 149,999;MOE; 150,000-199,999; MOE; above 200,000 (merge to 299,999, 300-499,999, 500,000 to 999,999 and 1M+); gross rent less than 200; 200-299; 300-499; 500-749, 750 to 999; 1000-1499; 1500+

1. Make income and rent categorical data.
2. merge all the years together.
3. run regression analysis and wls on income, rent and vacancy rate over time.
4. Panel regression and unfortunately maybe DID.